### PR TITLE
Fix isAlive compatible in threading

### LINKED ISSUE #7: Thread method isAlive compatible with python 3.9
* Faraday GTK Client version: 1.1.0
* Python version: 3.9
* Operating System: Parrot OS 4.10

### Description

On Debian testing based distro, thee default python has been upgraded to python3.9 which removed isAlive(). It makes application failed to stop (crashes after click on exit)

### What I Did

- Start Faraday-client
- Stop faraday client
- Client has this error while stopping
```
Original exception was:
Traceback (most recent call last):
  File "/usr/bin/faraday-client", line 11, in <module>
    load_entry_point('faraday-client==1.0.0', 'console_scripts', 'faraday-client')()
  File "/usr/lib/python3/dist-packages/faraday_client/start_client.py", line 448, in main
    start_faraday_client()
  File "/usr/lib/python3/dist-packages/faraday_client/start_client.py", line 227, in start_faraday_client
    exit_status = start()
  File "/usr/lib/python3/dist-packages/faraday_client/model/application.py", line 129, in start
    return self.__exit(exit_code)
  File "/usr/lib/python3/dist-packages/faraday_client/model/application.py", line 141, in __exit
    if self._model_controller.isAlive():
TypeError: 'NoneType' object is not callable
```
Link: `https://bugs.python.org/issue37804`

Fix method is edit `isAlive()` to `is_alive()` at https://github.com/infobyte/faraday-client/blob/master/faraday_client/model/application.py#L141
It worked well with python3.9.
It should be compatible with python2 (doc: `https://docs.python.org/2.7/library/threading.html`) and any older version of python3 (doc: `https://docs.python.org/3.5/library/threading.html`)

### PR DESCRIPTION
**Pull request by dmknght**
Fix #7

### CODE REVIEW

**Comment by dmknght** [comment]
Fix #9 
- Add Entry for URL in ForceLoginDialog
- Add Entry for URL in AuthDialog
- Fix a crash when user didn't login at faraday_client/persistence/server/server.py (Login bug makes server_url became None type)
Complete #5 
- The function `login` which asks user's login info in terminal now is called when user pass `--login` flag only
P/s: likely a new bug in check is_authen before calling ForceLoginDialog forces program to ask user login time to time.

**Comment by dmknght** [comment]
it is not a bug but the way it was created. ForceLogin was made without  `CONF.saveConfig()` so, my questions are, if devs can kindly check my PR:
- What if the server has 2FA and ForceLoginDialog is used for first login? It should be as same as AuthDialog which has 2FA Entry?
- Do ForceLoginDialog need `saveConfig()`? Did it created like that or it was created like template feature and it wasn't fully added?

**Comment by dmknght** [comment]
Force Login using GUI (no terminal prompt)
- problem 1: title
- problem 2: not start in center of screen
- problem 3: When user click exit (main widget), dialog isn't destroyed
image

AuthDialog that has new extra entry for custom URL. The URL is parsed from config or hard coded default localhost if it is empty
image

**Comment by dmknght** [comment]
Added title as "Faraday Login" (as same as AuthDialog) for ForceLoginDialog. now it only has 2 problems:
- Not start at center
- Dialog should be destroyed if user click on exit button or click Cancel (not very important).
p/s: likely it is GTK bug when dialog ins't destroyed if main app is shutting down

**Comment by aenima-x** [comment]
@dmknght we will check it. 
But keep in mind that this is deprecated. 
We are replacing it with https://github.com/infobyte/faraday-cli

**Comment by dmknght** [comment]
>  But keep in mind that this is deprecated.

That is a bad news to me. I think the gui is really useful to me. Is there any plan to improve GUI in the future or dev team will completely drop it? (Well i can understand the problem of maintaining a gui application and limitation of GUI framework but some improvement could be good)

>  We are replacing it with https://github.com/infobyte/faraday-cli
It is really nice!

**Comment by aenima-x** [comment]
@dmknght  We have a lot of problems with the dependencies, specially in new versions of osx. 
and we think the cli is better for devsecops. 
Please give it a try and tell us if you found some missing feature

**Comment by dmknght** [comment]
>  Please give it a try and tell us if you found some missing feature

I will create more pull requests then maybe can ask some guys to help me do it.
I'm having a short plan that remove CLI modules in this repo and try to do code improvement a little bit so maybe this repo can have new release (but i'm not sure about other platforms like Windows or OSX. I am having only Linux).

**Comment by aenima-x** [comment]
I would like to know why the new cli don't work for you.
That feedback will help us to make improvements.
Also we are working in a new api for faraday so eventually the GTK client will not work any more

**Comment by dmknght** [comment]
> I would like to know why the new cli don't work for you.

Oh no i haven't used it. I just knew it after you tell me in the topic.

The gtk client is still official client for the faraday on Parrot OS (and maybe Kali as well). And to me, it is easier to use zsh from GTK client to do pentest thing while using mouse to check information from GUI.

>  Also we are working in a new api for faraday so eventually the GTK client will not work any more

I would like to do improvement from my side for GTK and do the API change. I can ask some dude to help me with it. I think it is not very hard because Python is widely used. I can ask some friends and some devs from Parrot team for this. And in my opinion, with customized zsh profiles and some improvements, faraday GTK could be used as official application to do pentesting.

**Pull request closed without merging**
